// <auto-generated />
namespace _250ml_MVC4_2.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddOwnerToHappening : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddOwnerToHappening));
        
        string IMigrationMetadata.Id
        {
            get { return "201308211456079_AddOwnerToHappening"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
